# permissions for end users to view celerybrokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: celerybroker-viewer-role
rules:
- apiGroups:
  - celery.celeryproject.org
  resources:
  - celerybrokers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - celery.celeryproject.org
  resources:
  - celerybrokers/status
  verbs:
  - get
