// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v4

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Celery) DeepCopyInto(out *Celery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Celery.
func (in *Celery) DeepCopy() *Celery {
	if in == nil {
		return nil
	}
	out := new(Celery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Celery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryBroker) DeepCopyInto(out *CeleryBroker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryBroker.
func (in *CeleryBroker) DeepCopy() *CeleryBroker {
	if in == nil {
		return nil
	}
	out := new(CeleryBroker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryList) DeepCopyInto(out *CeleryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Celery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryList.
func (in *CeleryList) DeepCopy() *CeleryList {
	if in == nil {
		return nil
	}
	out := new(CeleryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CeleryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CelerySpec) DeepCopyInto(out *CelerySpec) {
	*out = *in
	out.Broker = in.Broker
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]CeleryWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CelerySpec.
func (in *CelerySpec) DeepCopy() *CelerySpec {
	if in == nil {
		return nil
	}
	out := new(CelerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryStatus) DeepCopyInto(out *CeleryStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryStatus.
func (in *CeleryStatus) DeepCopy() *CeleryStatus {
	if in == nil {
		return nil
	}
	out := new(CeleryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryWorker) DeepCopyInto(out *CeleryWorker) {
	*out = *in
	if in.TargetQueues != nil {
		in, out := &in.TargetQueues, &out.TargetQueues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resource.DeepCopyInto(&out.Resource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryWorker.
func (in *CeleryWorker) DeepCopy() *CeleryWorker {
	if in == nil {
		return nil
	}
	out := new(CeleryWorker)
	in.DeepCopyInto(out)
	return out
}
