name: 'Build'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: 'Test the operator'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup Golang version'
        uses: 'actions/setup-go@v1'
        with:
          go-version: '1.14.7'
      - name: 'Install kubebuilder'
        uses:  'RyanSiu1995/kubebuilder-action@v1'
      - name: 'Test the operator'
        run: 'make test'
  build:
    name: 'Building the binary'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup Golang version'
        uses: 'actions/setup-go@v1'
        with:
          go-version: '1.14.7'
      - name: 'Build the binary and lint code'
        run: 'make'
