name: 'Build'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: 'Test the operator'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup Golang version'
        uses: 'actions/setup-go@v1'
        with:
          go-version: '1.14.7'
      - name: 'Install kubebuilder'
        run: |-
          os=$(go env GOOS)
          arch=$(go env GOARCH)

          # download kubebuilder and extract it to tmp
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/

          # move to a long-term location and put it on your path
          # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
      - name: 'Test the operator'
        run: 'make test'
  build:
    name: 'Building the binary'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup Golang version'
        uses: 'actions/setup-go@v1'
        with:
          go-version: '1.14.7'
      - name: 'Build the binary and lint code'
        run: 'make'
