name: 'Build'
on:
- push
jobs:
  build:
    name: 'Building the binary'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'
    - name: 'Setup Golang version'
      uses: 'actions/setup-go@v1'
      with:
        go-version: '1.14.7'
    - name: 'Build the binary and lint code'
      run: 'make'
