name: 'E2E Test'
env:
  SDK_VERSION: 'v0.13.0'
on:
- push
jobs:
  e2e:
    name: 'E2E Test'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'
    - name: 'Setup Golang version'
      uses: 'actions/setup-go@v1'
      with:
        go-version: '1.13.5'
    - name: 'Build the image'
      run: 'make'
