name: 'E2E Test'
env:
  SDK_VERSION: 'v0.13.0'
on:
- push
jobs:
  e2e:
    name: 'E2E Test'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'
    - name: 'Setup Golang version'
      uses: 'actions/setup-go@v1'
      with:
        go-version: '1.13.5'
    - name: 'Install operator SDK'
      run: |-
        sudo curl -L https://github.com/operator-framework/operator-sdk/releases/download/${SDK_VERSION}/operator-sdk-${SDK_VERSION}-x86_64-linux-gnu -o /usr/bin/operator-sdk
        sudo chmod 777 /usr/bin/operator-sdk
    - name: 'Install Kubectl'
      run: |-
        sudo curl -L https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl -o /usr/bin/kubectl
        sudo chmod 777 /usr/bin/kubectl
    - name: 'Install kind and spin up local cluster'
      run: |-
        GO111MODULE="on" go get sigs.k8s.io/kind@v0.7.0
        kind create cluster
        kubectl cluster-info --context kind-kind
    - name: 'Build the image'
      run: |-
        operator-sdk build ryansiu1995/celery-operator:ci
    - name: 'Push the CI image to docker hub'
      run: |-
        docker login -u ryansiu1995 -p ${DOCKERHUB_PW}
        docker push ryansiu1995/celery-operator:ci
      env:
        DOCKERHUB_PW: '${{ secrets.DOCKERHUB_PW }}'
    - name: 'Run E2E Test'
      run: |-
        operator-sdk test local ./test/e2e
