name: 'E2E Test'
env:
  SDK_VERSION: 'v0.13.0'
on:
- push
jobs:
  image:
    name: 'Building CI Image'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'
    - name: 'Install operator SDK'
      run: |-
        sudo curl -L https://github.com/operator-framework/operator-sdk/releases/download/${SDK_VERSION}/operator-sdk-${SDK_VERSION}-x86_64-linux-gnu -o /usr/bin/operator-sdk
        sudo chmod 777 /usr/bin/operator-sdk
    - name: 'Build the image'
      run: |-
        operator-sdk build ryansiu1995/celery-operator:ci
    - name: 'Push the CI image to docker hub'
      run: |-
        docker login -u ryansiu1995 -p ${DOCKERHUB_PW}
        docker push ryansiu1995/celery-operator:ci
      env:
        DOCKERHUB_PW: '${{ secrets.DOCKERHUB_PW }}'
