name: 'E2E Test'
description: 'Setup an E2E test to ensure the operator works as expected'
author: 'Ryan Siu'
env:
  SDK_VERSION: v0.13.0
on:
- push
jobs:
  image:
    name: 'Building CI Image'
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: 'Install operator SDK'
        run: |-
          curl -L https://github.com/operator-framework/operator-sdk/releases/download/${SDK_VERSION}/operator-sdk-${SDK_VERSION}-x86_64-linux-gnu -o /usr/bin/operator-sdk && \
          chmod 777 /usr/bin/operator-sdk
      - name: 'Build the image'
        run: |-
          operator-sdk build ryansiu1995/celery-operator:ci
